model {
  file: "model.sdf"
}
name: "Black_Decker_CM2035B_12Cup_Thermal_Coffeemaker"
description: "Black & Decker CM2035B 12-Cup Thermal Coffeemaker"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Black"
}
annotations {
  key: "gtin"
  value: "00050875812123"
}
annotations {
  key: "sku"
  value: "00050875812123"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
